spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dong_lab?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
    mongodb:
      uri: mongodb://127.0.0.1:27017/dong_lab

  elasticsearch:
    uris: 127.0.0.1:9200
    username: elastic
    password: elastic

  kafka:
    bootstrap-servers: 127.0.0.1:9092

rocketmq:
  name-server: 127.0.0.1:9876

lab:
  redisson:
    address: redis://127.0.0.1:6379

  mq:
    active: local

  elasticsearch:
    enabled: false

  mongodb:
    enabled: false

  kafka:
    enabled: false

  rocketmq:
    enabled: false

  mariadb:
    enabled: false
    url: jdbc:mariadb://127.0.0.1:3307/dong_lab_replica?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
